name: Deploy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action (apply or destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_access_key_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_secret_access_key }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_session_token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Run Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            echo "Running Terraform Apply..."
            terraform apply -auto-approve
          else
            echo "Running Terraform Destroy..."
            terraform destroy -auto-approve
          fi

      - name: Terraform Output
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform output
